<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>scorpio_utilities</name>
  <version>0.0.1</version>
  <description>scorpio navigation support meta package</description>
  <maintainer email="lihanchen2004@163.com">Lihan Chen</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- scorpio_nav_bringup doesn't belong for recursive dependencies -->
  <depend>waypoint_rviz_plugin</depend>
  <depend>goalpoint_rviz_plugin</depend>
  <depend>teleop_rviz_plugin_plus</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
